### ISSUE TITLE
suggestion: add datapack support for plants and animals

### ISSUE THREAD

**Issue by gundami** [Zuiron/Photosynthesis#217]
as title
it will be more flexible to customize the plants and animals from other mods

**Comment by Zuiron** [comment]
yeaaaah. except it isnt that simple. because crops can be implemented in sooo many ways. i mean just to make this mod possible i had to change the code in minecraft for multiple crops with mixins. i dont think that would be viable. i might be wrong. and im not that good at making mods at all xD specially for the animals even harder i think.
