### ISSUE TITLE
Cobblemon Plants crashing when right clicked

### ISSUE THREAD

**Issue by floorcheese1** [Zuiron/Photosynthesis#250]
We have the Cobblemon mod added and it seems to bring up some problems with some of the plants(like the medicinal leek and mints) as it crashes when right clicked with anything in hand

![image](https://github.com/user-attachments/assets/79cd0b94-a8a2-497c-9a55-78737a971fe2)
![image](https://github.com/user-attachments/assets/72ea204e-200e-4de4-8f6e-107d64a7736d)

**Comment by Mr-iMikeyyy** [comment]
We experience this on our server as well, particularly revival herbs

**Comment by Mr-iMikeyyy** [comment]
Explanation given to me from one of my players who likes diving into bugs, take with a grain of salt. "when the mod Wthit tries to display a certain block tag for it fails and displays an error code but interacting with the medincial leek changes said tag which crashes the user because the mod cant display a changed error code".

**Comment by Zuiron** [comment]
solved in https://github.com/Zuiron/Photosynthesis/commit/36bb2fac8f44385c50444c3240f89c569bb21874

new update live: https://modrinth.com/mod/photosynthesis/version/1.20.1-0.0.25
